version: '2'
services:
    frontend:
      build: ./frontend
      volumes:
        - ./frontend/source:/home/develop/ #changed here for your $(pwd)
      ports:
        - "3000:3000"
        - "4200:4200"
        - "49153:49153"
      expose: 
        - "3000"
        - "4200"
        - "49153"

      command: ng server --host 0.0.0.0 --port 4200  --live-reload-port 49153
    
    # backend:



      





